import type {Check,Officer,Entry,PersonalLoad} from './domain';
import {dateTime,needsJustification,platoonOf,platoonName} from './domain';
type Filters={category:string;condition:string;onlyDivergence:boolean};
const download=(buffer:BlobPart,name:string,mime:string)=>{const url=URL.createObjectURL(new Blob([buffer],{type:mime}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
export async function exportReport(format:'pdf'|'xlsx',checks:Check[],officers:Officer[],filters:Filters){
 const crew=(c:Check)=>c.crew_labels?.length?c.crew_labels.join('; '):c.crew.map(id=>{const o=officers.find(x=>x.id===id);return o?`${o.name} (${o.registration})`:id}).join('; ');
 const visible=(e:Entry)=>(filters.category==='todos'||e.category===filters.category)&&(filters.condition==='todos'||e.condition===filters.condition)&&(!filters.onlyDivergence||needsJustification(e,e.expected||0));
 const notes=(c:Check)=>[c.notes,...(c.corrections||[]).map(x=>'Retificação: '+x.actor_name+' ('+(x.actor_registration||'conta institucional')+') · '+dateTime(x.created_at)+' · '+x.reason+': '+x.correction)].filter(Boolean).join('\n');
 const rows=checks.flatMap(c=>c.entries.filter(visible).map(e=>[c.id,c.city,dateTime(c.finalized_at),c.actor_name,crew(c),e.category||'',e.name||'',e.serial||'',e.city||c.city,e.location||c.city,e.expected||0,e.quantity||0,(e.quantity||0)-(e.expected||0),e.condition,e.identification?'Sim':'Não',e.notes,notes(c)]));
 if(!rows.length)throw new Error('Nenhum material corresponde aos filtros.');
 const headings=['Registro','Município do serviço','Data e hora (Brasília)','Responsável','Guarnição / matrículas','Categoria','Material','Identificação','Município patrimonial','Localização na conferência','Quantidade prevista','Quantidade conferida','Diferença','Condição','Identificação divergente','Observações do material','Observações do serviço'];
 const filename='gestao-pelotoes-conferencias-'+new Date().toISOString().slice(0,10);
 if(format==='xlsx'){
  const ExcelJS=(await import('exceljs')).default;const workbook=new ExcelJS.Workbook();workbook.creator='4º Pelotão · 80ª CIPM';workbook.created=new Date();
  const sheet=workbook.addWorksheet('Conferências',{views:[{state:'frozen',ySplit:4}]});
  sheet.mergeCells(1,1,1,17);sheet.getCell('A1').value='POLÍCIA MILITAR DA BAHIA · 80ª CIPM · GESTÃO DE PELOTÕES';sheet.getCell('A1').font={size:16,bold:true,color:{argb:'FFFFFFFF'}};sheet.getCell('A1').fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF152A45'}};sheet.getRow(1).height=34;
  sheet.mergeCells(2,1,2,17);sheet.getCell('A2').value='Relatório de conferência · Emitido em '+dateTime(new Date().toISOString());sheet.getRow(2).height=24;
  const header=sheet.getRow(4);header.values=headings;header.height=32;header.eachCell(c=>{c.font={bold:true,color:{argb:'FFFFFFFF'}};c.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF233C5C'}};c.alignment={vertical:'middle',wrapText:true}});
  rows.forEach(row=>{const r=sheet.addRow(row);r.height=42;r.eachCell(c=>{c.alignment={wrapText:true,vertical:'middle'};c.border={bottom:{style:'thin',color:{argb:'FFE1E7EF'}}}});if(Number(row[12])!==0)r.getCell(13).font={bold:true,color:{argb:'FFB53739'}}});
  sheet.columns.forEach((c,i)=>c.width=[38,20,24,25,45,18,28,23,22,22,17,18,14,20,19,50,45][i]);sheet.autoFilter={from:'A4',to:'Q'+(rows.length+4)};
  sheet.pageSetup={orientation:'landscape',fitToPage:true,fitToWidth:1,fitToHeight:0,paperSize:9};
  const validation=workbook.addWorksheet('Validação');validation.columns=[{width:42},{width:66}];validation.addRow(['4º PELOTÃO · 80ª CIPM','Validação administrativa']);validation.addRow(['Emitido em',dateTime(new Date().toISOString())]);checks.forEach(c=>{validation.addRow([]);validation.addRow(['Registro',c.id]);validation.addRow(['Município / finalização',`${c.city} · ${dateTime(c.finalized_at)}`]);validation.addRow(['Responsável autenticado',c.actor_name]);validation.addRow(['Identificador da conta',c.actor]);validation.addRow(['Guarnição',crew(c)]);validation.addRow(['Assinatura do responsável','________________________________________']);validation.addRow(['Validação do comando','________________________________________'])});
  const buffer=await workbook.xlsx.writeBuffer();download(buffer as unknown as BlobPart,filename+'.xlsx','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');return;
 }
 const {jsPDF}=await import('jspdf');const {default:autoTable}=await import('jspdf-autotable');const doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});
 let logo:string|null=null;try{const response=await fetch(import.meta.env.BASE_URL+'brasao.png');const blob=await response.blob();logo=await new Promise<string>(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.readAsDataURL(blob)})}catch{}
 checks.forEach((c,index)=>{
  if(index)doc.addPage();doc.setFillColor(21,42,69);doc.rect(0,0,297,29,'F');if(logo)doc.addImage(logo,'PNG',12,3,22,22);doc.setTextColor(255,255,255);doc.setFontSize(14);doc.setFont('helvetica','bold');doc.text('POLÍCIA MILITAR DA BAHIA | 80ª CIPM | PELOTÕES',39,12);doc.setFontSize(10);doc.setFont('helvetica','normal');doc.text('RELATÓRIO DE CONFERÊNCIA DE MATERIAIS OPERACIONAIS',39,20);doc.setTextColor(25,39,57);doc.setFontSize(11);doc.text(`Município: ${c.city} (${platoonName(platoonOf(c.city)||'')})     Finalização: ${dateTime(c.finalized_at)} (Brasília)`,12,38);doc.text('Responsável autenticado: '+c.actor_name,12,45);const crewLines=doc.splitTextToSize('Guarnição: '+crew(c),272);doc.text(crewLines,12,52);
  autoTable(doc,{startY:57+(crewLines.length-1)*5,head:[['Material / identificação','Vinculação / local','Previsto','Conferido','Diferença','Condição','Observações']],body:c.entries.filter(visible).map(e=>[`${e.name}\n${e.serial||''}`,`${e.city||c.city}\n${e.location||c.city}`,e.expected??0,e.quantity??0,(e.quantity||0)-(e.expected||0),e.condition,`${e.identification?'Identificação divergente. ':''}${e.notes}`]),styles:{fontSize:9,cellPadding:2,overflow:'linebreak'},headStyles:{fillColor:[35,60,92]},alternateRowStyles:{fillColor:[243,246,250]},margin:{left:12,right:12,bottom:18},columnStyles:{0:{cellWidth:57},1:{cellWidth:39},2:{cellWidth:19},3:{cellWidth:23},4:{cellWidth:21},5:{cellWidth:28},6:{cellWidth:86}}});
  let y=(doc as any).lastAutoTable.finalY+9;const notesLines=doc.splitTextToSize('Observações do serviço: '+(notes(c)||'Sem observações.'),270);if(y+notesLines.length*4+32>190){doc.addPage();y=20}doc.setFontSize(9);doc.text(notesLines,12,y);y+=notesLines.length*4+14;doc.line(15,y,125,y);doc.line(160,y,280,y);doc.text('Assinatura do responsável pela conferência',15,y+5);doc.text('Validação administrativa / comando',160,y+5);doc.setFontSize(7);doc.text('Registro: '+c.id,12,y+13);doc.text('Conta autenticada: '+c.actor,12,y+17);
 });
 const total=doc.getNumberOfPages();for(let page=1;page<=total;page++){doc.setPage(page);doc.setTextColor(90,100,115);doc.setFontSize(8);doc.text('80ª CIPM · Emitido em '+dateTime(new Date().toISOString()),12,202);doc.text(`${page} / ${total}`,279,202)}doc.save(filename+'.pdf');
}
export async function exportDailyLoad({load,check,officer}:{load:PersonalLoad;check:Check;officer:{name:string;registration:string}}){
 const {jsPDF}=await import('jspdf');const {default:autoTable}=await import('jspdf-autotable');const doc=new jsPDF({unit:'mm',format:'a4'});
 doc.setFillColor(21,42,69);doc.rect(0,0,210,29,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(12);doc.text('POLÍCIA MILITAR DA BAHIA | 80ª CIPM | PELOTÕES',12,12);doc.setFontSize(10);doc.text('CARGA INDIVIDUAL DIÁRIA DE MATERIAL DO DPM',12,21);
 doc.setTextColor(25,39,57);doc.setFont('helvetica','normal');doc.setFontSize(10);let y=40;
 for(const line of [`Município do serviço: ${load.city} (${platoonName(platoonOf(load.city)||'')})`,`Dia do serviço: ${load.service_day.split('-').reverse().join('/')}`,`Policial: ${load.officer_name}`,`Matrícula: ${officer.registration}`,`Carga assumida em: ${dateTime(load.created_at)} (Brasília)`,`Conferência do DPM: ${check.actor_name}`,`Conferência realizada em: ${dateTime(check.finalized_at)} (Brasília)`,`Situação: ${load.status==='ativa'?'Ativa - material reservado':'Devolvida em '+dateTime(load.returned_at)}`,...(check.deleted_at?['Conferência posteriormente excluída pelo gestor em '+dateTime(check.deleted_at)]:[])]){const lines=doc.splitTextToSize(line,186);doc.text(lines,12,y);y+=lines.length*5+2;}
 autoTable(doc,{startY:y+2,head:[['Material / identificação','Quantidade assumida','Condição na conferência']],body:load.entries.map(e=>[e.name+(e.serial?'\n'+e.serial:''),e.quantity,e.condition]),styles:{fontSize:10,cellPadding:3,overflow:'linebreak'},headStyles:{fillColor:[35,60,92]},alternateRowStyles:{fillColor:[243,246,250]},margin:{left:12,right:12,bottom:20},columnStyles:{0:{cellWidth:105},1:{cellWidth:32},2:{cellWidth:49}}});
 y=(doc as any).lastAutoTable.finalY+10;const notes=doc.splitTextToSize('Observações: '+(load.notes||'Sem observações.')+'\n'+(check.corrections||[]).map(c=>'Retificação de conferência: '+c.actor_name+' · '+dateTime(c.created_at)+' · '+c.correction).join('\n'),186);if(y+notes.length*5+35>275){doc.addPage();y=20}doc.text(notes,12,y);y+=notes.length*5+15;doc.line(25,y,185,y);doc.text('Assinatura do policial responsável',68,y+6);doc.setFontSize(8);doc.text('Carga: '+load.id,12,y+16);doc.text('Conferência: '+load.check_id,12,y+21);
 const total=doc.getNumberOfPages();for(let p=1;p<=total;p++){doc.setPage(p);doc.setFontSize(8);doc.setTextColor(90,100,115);doc.text('Emitido em '+dateTime(new Date().toISOString())+' (Brasília)',12,289);doc.text(`${p} / ${total}`,187,289)}doc.save(`gestao-pelotoes-carga-${load.service_day}-${officer.registration}.pdf`);
}
