import {useState} from 'react';
import {PLATOONS,dateTime,localDay} from '@/lib/domain';
import {Dialog,DialogContent,DialogTitle} from '@/components/ui/dialog';
import {ClipboardCheck,MapPin,Eye,RefreshCw,PackageCheck,Users,ArrowUpRight,CheckCircle2,Clock,TriangleAlert,X,ShieldCheck} from 'lucide-react';
type Conference={id:string;day:string;at:string;responsible:string;crew:string[];checked:number};
type Load={id:string;officer_name:string;registration:string;day:string;at:string;returned_at:string|null;status:string;in_period:boolean;quantity:number;entries:{name:string;serial:string|null;quantity:number;condition:string}[]};
type City={city:string;platoon_id:string;status:string;pending:number;missing:number;divergences:number;last_at:string|null;loads:number;loaded_quantity:number;loads_in_period:number;units_in_period:number;crew_total:number;crew_loaded:number;details_allowed:boolean;conference:{status:string;by_commander:boolean;at:string|null;day:string|null;responsible:string;count:number};conference_records:Conference[];load_records:Load[]};
type Props={dashboard:City[];period:{start:string;end:string};refreshPeriod:(period:{start:string;end:string})=>Promise<any>;canManage:(city:string)=>boolean;canOperate:(city:string)=>boolean;onInventory:(city:string)=>void;onCheck:(city:string)=>void};
const tones:Record<string,string>={conferida:'green',pendente:'amber',divergencia:'red',andamento:'blue'};
const labels:Record<string,string>={conferida:'Conferida',pendente:'Pendente',divergencia:'Com divergência',andamento:'Em andamento'};
const day=(value:string)=>value?value.split('-').reverse().join('/'):'—';
export default function OperationalBoard({dashboard,period,refreshPeriod,canManage,canOperate,onInventory,onCheck}:Props){
 const [platoon,setPlatoon]=useState('todos'),[status,setStatus]=useState('todos'),[city,setCity]=useState('todos'),[start,setStart]=useState(period.start||localDay()),[end,setEnd]=useState(period.end||localDay()),[opened,setOpened]=useState(''),[tab,setTab]=useState<'conference'|'loads'>('conference');
 const filtered=dashboard.filter(d=>(platoon==='todos'||d.platoon_id===platoon)&&(city==='todos'||d.city===city)&&(status==='todos'||d.status===status));
 const selected=dashboard.find(d=>d.city===opened);
 function open(d:City,section:'conference'|'loads'){setOpened(d.city);setTab(section)}
 return <>
  <section className="operations-heading"><div><p className="eyebrow">80ª CIPM · ACOMPANHAMENTO INTEGRADO</p><h2>Conferência e carga do DPM</h2><p>Acompanhe a conferência do comandante e o recebimento individual dos materiais.</p></div><span className="period-chip"><Clock size={15}/>{day(period.start)}{period.end!==period.start?' a '+day(period.end):''}</span></section>
  <form className="report-filters board-filters" onSubmit={e=>{e.preventDefault();void refreshPeriod({start,end})}}>
   <label className="field">Pelotão<select value={platoon} onChange={e=>{setPlatoon(e.target.value);setCity('todos')}}><option value="todos">Todos autorizados</option>{PLATOONS.filter(p=>dashboard.some(d=>d.platoon_id===p.id)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
   <label className="field">Município<select value={city} onChange={e=>setCity(e.target.value)}><option value="todos">Todos autorizados</option>{dashboard.filter(d=>platoon==='todos'||d.platoon_id===platoon).map(d=><option key={d.city}>{d.city}</option>)}</select></label>
   <label className="field">Conferência<select value={status} onChange={e=>setStatus(e.target.value)}><option value="todos">Todas as situações</option>{Object.entries(labels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label>
   <label className="field">Data inicial<input type="date" required value={start} onChange={e=>setStart(e.target.value)}/></label><label className="field">Data final<input type="date" required min={start} value={end} onChange={e=>setEnd(e.target.value)}/></label><button className="btn secondary" type="submit"><RefreshCw size={16}/> Atualizar</button>
  </form>
  <section className="board-overview" aria-label="Resumo do período">
   <div><MapPin size={20}/><span><strong>{filtered.length}</strong><small>DPMs na seleção</small></span></div>
   <div><ClipboardCheck size={20}/><span><strong>{filtered.filter(d=>d.conference?.by_commander).length}</strong><small>DPMs conferidos</small></span></div>
   <div><Users size={20}/><span><strong>{filtered.reduce((n,d)=>n+(d.loads_in_period||0),0)}</strong><small>Cargas no período</small></span></div>
   <div><TriangleAlert size={20}/><span><strong>{filtered.reduce((n,d)=>n+d.pending,0)}</strong><small>Pendências atuais</small></span></div>
  </section>
  {PLATOONS.filter(p=>filtered.some(d=>d.platoon_id===p.id)).map(p=><section className="platoon-section" key={p.id}><div className="section-heading"><h2>{p.name}</h2><small>{canManage(p.cities[0])?'Gestão do pelotão':'Consulta dos indicadores'}</small></div><div className="operation-grid">{filtered.filter(d=>d.platoon_id===p.id).map(d=>{
   const completed=d.conference?.by_commander,progress=d.conference?.status==='rascunho';
   const loadDone=d.crew_total>0&&d.crew_loaded>=d.crew_total;
   return <article className={'operation-card '+(tones[d.status]||'')} key={d.city}>
    <header className="operation-card-head"><div className="dpm-icon"><MapPin size={21}/></div><div><small>DESTACAMENTO DE POLÍCIA MILITAR</small><h3>{d.city}</h3></div><span className={'badge '+tones[d.status]}>{labels[d.status]}</span></header>
    <div className="operation-stages">
     <button className="operation-stage" onClick={()=>open(d,'conference')} aria-label={'Ver conferência de '+d.city}>
      <span className={'stage-icon '+(completed?'green':progress?'blue':'amber')}>{completed?<CheckCircle2 size={21}/>:<ClipboardCheck size={21}/>}</span><span className="stage-copy"><strong>Conferência do comandante</strong><span>{completed?d.conference.responsible:progress?'Conferência em andamento':'Aguardando conferência'}</span><small>{d.conference?.at?dateTime(d.conference.at):'Nenhuma finalização no período'}</small></span><span className={'stage-state '+(completed?'green':progress?'blue':'amber')}>{completed?'Realizada':progress?'Em andamento':'Pendente'}<ArrowUpRight size={14}/></span>
     </button>
     <button className="operation-stage" onClick={()=>open(d,'loads')} aria-label={'Ver cargas de '+d.city}>
      <span className={'stage-icon '+(loadDone?'green':d.loads_in_period?'blue':'neutral')}><PackageCheck size={21}/></span><span className="stage-copy"><strong>Cargas individuais</strong><span>{d.crew_total?`${d.crew_loaded} de ${d.crew_total} integrantes com carga`:d.loads_in_period?`${d.loads_in_period} carga(s) registrada(s)`:'Nenhuma carga no período'}</span><small>{d.crew_total?'Guarnição da última conferência do período':'Cada policial registra seu recebimento'}</small></span><span className={'stage-state '+(loadDone?'green':d.loads_in_period?'blue':'neutral')}>{loadDone?'Registradas':d.loads_in_period?'Parcial':'Aguardando'}<ArrowUpRight size={14}/></span>
     </button>
    </div>
    <div className="operation-totals"><span><strong>{d.units_in_period||0}</strong><small>Unidades recebidas<br/>no período</small></span><span><strong>{d.loaded_quantity}</strong><small>Unidades ainda<br/>em carga ativa</small></span><span className={d.pending?'has-pending':''}><strong>{d.pending}</strong><small>Pendências<br/>atuais</small></span></div>
    <footer className="operation-card-foot"><button className="operation-detail-button" onClick={()=>open(d,'loads')}>Ver policiais e materiais <ArrowUpRight size={16}/></button><div>{canManage(d.city)&&<button aria-label={'Ver inventário de '+d.city} onClick={()=>onInventory(d.city)}><Eye size={15}/> Inventário</button>}{canOperate(d.city)&&<button aria-label={'Conferir materiais de '+d.city} onClick={()=>onCheck(d.city)}><ClipboardCheck size={15}/> Conferir</button>}</div></footer>
   </article>;
  })}</div></section>)}
  {!filtered.length&&<p className="panel form-body">Nenhum município corresponde aos filtros.</p>}
  {selected&&<Dialog open onOpenChange={open=>{if(!open)setOpened('')}}><DialogContent className="modal operation-dialog" showCloseButton={false} aria-describedby="operation-detail-description"><div className="modal-head"><div><p className="eyebrow">SERVIÇO DO DPM · {PLATOONS.find(p=>p.id===selected.platoon_id)?.name}</p><DialogTitle>{selected.city}</DialogTitle></div><button className="icon-btn" aria-label="Fechar detalhes" onClick={()=>setOpened('')}><X size={20}/></button></div><div className="operation-detail-body"><p id="operation-detail-description" className="detail-period">Período: {day(period.start)}{period.end!==period.start?' a '+day(period.end):''}. As cargas ativas de dias anteriores também são identificadas.</p><div className="operation-detail-tabs"><button className={tab==='conference'?'selected':''} onClick={()=>setTab('conference')}><ClipboardCheck size={17}/> Conferência do comandante</button><button className={tab==='loads'?'selected':''} onClick={()=>setTab('loads')}><PackageCheck size={17}/> Cargas por policial</button></div>
   {tab==='conference'?<><div className={'operation-result '+(selected.conference?.by_commander?'green':'amber')}><ShieldCheck size={24}/><div><strong>{selected.conference?.by_commander?'Material conferido pelo comandante da guarnição':selected.conference?.status==='rascunho'?'Conferência ainda em andamento':'Material ainda não conferido no período'}</strong><p>{selected.conference?.responsible||'Aguardando registro'}{selected.conference?.at?' · '+dateTime(selected.conference.at):''}</p></div></div>{selected.details_allowed&&selected.conference_records.map(c=><section className="conference-detail" key={c.id}><header><h3>Conferência de {day(c.day)}</h3><span className="badge green">Finalizada</span></header><p><strong>Comandante da guarnição:</strong> {c.responsible}</p><p>{dateTime(c.at)} · {c.checked} materiais conferidos</p><h4>Policiais da guarnição</h4><div className="crew-names">{c.crew.map((name,i)=><span key={i}><Users size={14}/>{name}</span>)}</div></section>)}</>:<><div className="detail-load-summary"><span><strong>{selected.loads_in_period}</strong> cargas no período</span><span><strong>{selected.units_in_period}</strong> unidades recebidas no período</span><span><strong>{selected.loads}</strong> cargas ainda ativas</span></div>{selected.details_allowed?selected.load_records.length?selected.load_records.map(l=><section className="police-load-detail" key={l.id}><header><div><h3>{l.officer_name}</h3><p>{l.registration?'Matrícula '+l.registration+' · ':''}{day(l.day)}</p></div><span className={'badge '+(l.status==='ativa'?'blue':'green')}>{l.status==='ativa'?'Em carga':'Devolvida'}</span></header><div className="load-detail-meta"><span>Recebimento: {dateTime(l.at)}</span><strong>{l.quantity} unidade(s) recebida(s)</strong></div>{!l.in_period&&<p className="prior-load-note">Carga de dia anterior, ainda ativa.</p>}<div className="table-wrap"><table className="load-material-table"><thead><tr><th>Material / identificação</th><th>Quantidade</th></tr></thead><tbody>{l.entries.map((e,i)=><tr key={i}><td><strong>{e.name}</strong>{e.serial&&<small>{e.serial}</small>}</td><td>{e.quantity}</td></tr>)}</tbody></table></div>{l.returned_at&&<p className="load-returned">Devolução registrada: {dateTime(l.returned_at)}</p>}</section>):<div className="detail-empty"><PackageCheck size={30}/><strong>Nenhuma carga registrada</strong><p>Os policiais e as quantidades recebidas aparecerão aqui após o registro da carga individual.</p></div>:null}</>}
   {!selected.details_allowed&&<div className="detail-restricted"><ShieldCheck size={22}/><p>Você pode acompanhar os indicadores deste município. Os detalhes dos policiais e materiais estão disponíveis para o comando do respectivo pelotão e os gestores gerais.</p></div>}
  </div><div className="modal-foot"><button className="btn secondary" onClick={()=>setOpened('')}>Fechar</button></div></DialogContent></Dialog>}
 </>;
}
