import {useState,useEffect} from 'react';
import {Download,Package,CheckCircle2} from 'lucide-react';
import {dateTime,localDay,type Item,type Check,type PersonalLoad} from '@/lib/domain';
import {dailyReport} from '@/lib/api';
type Props={loads:PersonalLoad[];checks:Check[];items:Item[];user:{id:string;officer_id:string|null;role:string;is_global?:boolean;managementCities?:string[];capabilities?:Record<string,boolean>};mutate:(payload:any,message:string,close?:boolean)=>Promise<any>;refresh:(city:string)=>Promise<any>;cities:string[];reportsOnly?:boolean;initialCity?:string};
export default function PersonalLoads({loads,checks,items,user,mutate,refresh,reportsOnly=false,cities,initialCity='Condeúba'}:Props){
 const [city,setCity]=useState(cities.includes(initialCity)?initialCity:cities[0]||''),[quantities,setQuantities]=useState<Record<string,number>>({}),[notes,setNotes]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[returnId,setReturnId]=useState(''),[returnNotes,setReturnNotes]=useState('');
 useEffect(()=>{if(!reportsOnly)void refresh(city)},[city,reportsOnly]);
 const today=localDay(),mine=loads.filter(l=>l.actor===user.id),already=mine.some(l=>l.service_day===today),check=checks.find(c=>c.city===city&&c.service_day===today&&c.status==='finalizada'&&!c.deleted_at&&c.crew.includes(user.officer_id||''));
 const invalidQuantity=(q:number,max:number)=>!Number.isInteger(q)||q<0||q>max;
 const list=items.filter(i=>!i.deleted_at&&i.location===city&&i.quantity>0).map(i=>({...i,available:Math.max(0,Math.min(i.quantity,check?.entries.find(e=>e.id===i.id)?.quantity||0)-(i.reserved||0))}));
 async function pdf(id:string){setBusy(true);setError('');try{const data=await dailyReport(id);const {exportDailyLoad}=await import('@/lib/export');await exportDailyLoad(data);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function save(){setBusy(true);setError('');try{const result=await mutate({action:'save-load',checkId:check?.id,entries:list.map(i=>({id:i.id,quantity:quantities[i.id]||0})),notes},'Carga individual registrada. Seu PDF diário está disponível.',false);if(result){setQuantities({});setNotes('');setConfirmed(false);}}finally{setBusy(false)}}
 return <>{error&&<p className="inline-error" role="alert">{error}</p>}{!reportsOnly&&<section className="panel"><div className="panel-head"><div><h2><Package size={19}/> Minha carga do material do DPM</h2><p>Uma carga por dia. O material fica reservado até você registrar a devolução.</p></div></div><div className="form-body"><label className="field">Município em que assumiu o serviço<select value={city} onChange={e=>{setCity(e.target.value);setQuantities({});setConfirmed(false)}}>{cities.map(c=><option key={c}>{c}</option>)}</select></label>{already?<p className="small-notice">Sua carga de hoje já foi registrada e está no histórico abaixo. Você pode gerar o PDF e registrar a devolução.</p>:!user.officer_id?<p className="small-notice">Entre com sua matrícula para registrar sua carga individual.</p>:!check?<p className="small-notice">Aguarde a conferência de hoje pelo comandante da guarnição. Seu nome deve constar na guarnição deste município.</p>:<><p className="small-notice">Conferência do DPM: {check.actor_name} · {dateTime(check.finalized_at)}. Informe somente os materiais que você retirou.</p><div className="table-wrap"><table><thead><tr><th>Material / identificação</th><th>Encontrado no DPM</th><th>Disponível</th><th>Quantidade que retirei</th></tr></thead><tbody>{list.map(i=><tr key={i.id}><td><strong>{i.name}</strong><small>{i.serial||''}</small></td><td>{check.entries.find(e=>e.id===i.id)?.quantity||0}</td><td>{i.available}</td><td><input aria-label={'Quantidade de '+i.name+(i.serial?' '+i.serial:'')} type="number" min="0" max={i.available} inputMode="numeric" disabled={!i.available} value={quantities[i.id]||0} onChange={e=>{setQuantities(q=>({...q,[i.id]:Number(e.target.value)}));setConfirmed(false)}}/></td></tr>)}</tbody></table></div><label className="field">Observações da carga<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><label className="checkbox-line"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> Confirmo os materiais que retirei e assumi individualmente.</label><p className="small-notice">A quantidade assumida deve ser inteira e não pode superar o disponível. Se outro policial retirar o material, atualize antes de confirmar.</p><button className="btn primary" disabled={busy||!confirmed||!Object.values(quantities).some(q=>q>0)||list.some(i=>invalidQuantity(quantities[i.id]||0,i.available))} onClick={()=>void save()}>Registrar minha carga</button></>}</div></section>}
 <section className="panel"><div className="panel-head"><div><h2>{reportsOnly?'Meus PDFs diários':'Histórico das cargas'}</h2><p>O relatório fica disponível para o policial responsável, por dia e município do serviço.</p></div></div>{(user.role==='policial'?mine:loads).length?<div className="load-history">{(user.role==='policial'?mine:loads).map(l=><article className="load-card" key={l.id}><div><h3>{l.city} · {l.service_day.split('-').reverse().join('/')}</h3><strong>{l.officer_name}</strong><p>{l.entries.length} materiais · Assumidos em {dateTime(l.created_at)}</p><p>{l.status==='ativa'?'Carga ativa · material reservado':'Devolvida em '+dateTime(l.returned_at)}</p><details><summary>Ver materiais assumidos</summary><ul>{l.entries.map(e=><li key={e.id}>{e.quantity} × {e.name}{e.serial?' · '+e.serial:''}</li>)}</ul></details></div><div className="load-actions"><button className="btn secondary" disabled={busy} onClick={()=>void pdf(l.id)}><Download size={16}/> PDF diário</button>{!reportsOnly&&l.status==='ativa'&&(l.actor===user.id||user.is_global||user.capabilities?.movements&&user.managementCities?.includes(l.city))&&<button className="btn secondary" disabled={busy} onClick={()=>{setReturnId(l.id);setReturnNotes('')}}><CheckCircle2 size={16}/> Registrar devolução</button>}</div>{returnId===l.id&&<div className="load-return"><p>Confirme que todos os materiais desta carga foram devolvidos fisicamente ao DPM.</p>{l.actor!==user.id&&<label className="field">Justificativa do gestor<textarea required value={returnNotes} onChange={e=>setReturnNotes(e.target.value)}/></label>}<button className="btn primary" disabled={busy||l.actor!==user.id&&!returnNotes.trim()} onClick={async()=>{setBusy(true);try{const ok=await mutate({action:'return-load',id:l.id,confirmReturn:true,notes:returnNotes},'Devolução registrada. Os materiais estão disponíveis novamente.',false);if(ok)setReturnId('')}finally{setBusy(false)}}}>Confirmar devolução física</button><button className="btn secondary" onClick={()=>setReturnId('')}>Cancelar</button></div>}</article>)}</div>:<div className="form-body"><p>Nenhuma carga individual registrada ainda.</p></div>}</section></>;
}
