import {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Loader2,LogIn,ShieldCheck} from 'lucide-react';
import type {Session} from '@supabase/supabase-js';
import {initialize,supabase,loginIdentity,configureAdministrator} from './lib/api';
import Platform from './platform';
import './styles.css';
function App(){
 const [loading,setLoading]=useState(true),[configured,setConfigured]=useState(false),[session,setSession]=useState<Session|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[setupToken,setSetupToken]=useState(''),[mode,setMode]=useState<'login'|'password'|'setup'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState('');
 useEffect(()=>{let alive=true,unsubscribe:(()=>void)|undefined;const recovery=new URLSearchParams(location.hash.slice(1)).get('type')==='recovery';if(recovery)setMode('password');initialize().then(async client=>{if(!alive)return;const {data:listener}=client.auth.onAuthStateChange((event,current)=>{if(!alive)return;setSession(current);if(event==='PASSWORD_RECOVERY')setMode('password')});unsubscribe=()=>listener.subscription.unsubscribe();const {data}=await client.auth.getSession();if(!alive)return;setSession(data.session);setConfigured(true);}).catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false;unsubscribe?.()}},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{let result;if(mode==='setup'){await configureAdministrator(setupToken,password);history.replaceState(null,'',location.pathname);setMode('login');result=await supabase().auth.signInWithPassword({email:loginIdentity('4º Pelotão'),password});}else if(mode==='login')result=await supabase().auth.signInWithPassword({email:loginIdentity(email),password});else result=await supabase().auth.updateUser({password});if(result.error)throw result.error;if(mode==='password'){setMessage('Senha atualizada.');setPassword('');setMode('login')}}catch(e){const msg=(e as Error).message;setError(msg==='Invalid login credentials'?'Matrícula/login ou senha inválidos.':msg==='Email not confirmed'?'Procure o gestor para regularizar seu acesso.':msg.includes('rate limit')?'Limite de tentativas atingido. Aguarde e tente novamente.':msg)}finally{setBusy(false)}}
 if(session&&mode!=='password'&&mode!=='setup')return <Platform/>;
 return <div className="entry-screen"><div className="entry-card"><img src={import.meta.env.BASE_URL+'brasao.png'} alt="Brasão do 4º Pelotão"/><p className="eyebrow">POLÍCIA MILITAR DA BAHIA · 80ª CIPM</p><h1>Gestão operacional<br/>4º Pelotão</h1><p>Conferência de serviço, inventários e cautelas de Condeúba, Cordeiros e Mortugaba.</p>{loading?<p className="loading"><Loader2 className="spin"/> Preparando acesso…</p>:<>{error&&<p className="auth-error" role="alert">{error}</p>}{message&&<p className="auth-message" role="status">{message}</p>}{configured&&<form className="auth-form" onSubmit={submit}><h2>{mode==='login'?'Acesso individual':mode==='setup'?'Definir senha do 4º Pelotão':'Definir nova senha'}</h2>{mode==='setup'&&<><p>Login administrativo: <strong>4º Pelotão</strong>. Defina uma senha de pelo menos 12 caracteres.</p><label className="field">Código de autorização<input required type="password" autoComplete="off" minLength={64} maxLength={64} value={setupToken} onChange={e=>setSetupToken(e.target.value)} /></label></>}{mode==='login'&&<label className="field">Matrícula ou login administrativo<input type="text" required autoComplete="username" placeholder="Matrícula ou 4º Pelotão" value={email} onChange={e=>setEmail(e.target.value)}/></label>}{<label className="field">{mode==='password'?'Nova senha':'Senha'}<input required type="password" minLength={mode==='login'?1:12} autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label>}<button className="btn primary" disabled={busy}>{busy?<Loader2 size={17} className="spin"/>:<LogIn size={17}/>} {mode==='login'?'Entrar':mode==='setup'?'Definir senha e entrar':'Atualizar senha'}</button>{mode==='login'?<><p className="auth-help">Use sua matrícula e a senha fornecida pelo gestor. Para criar o acesso ou redefinir a senha, procure o gestor do pelotão.</p><div className="auth-links"><button type="button" onClick={()=>{setMode('setup');setError('');setMessage('');setPassword('')}}>Configuração inicial do gestor</button></div></>:mode==='setup'&&<button type="button" className="text-link" onClick={()=>{setMode('login');setError('');setSetupToken('');setPassword('')}}>Voltar ao acesso</button>}</form>}<small><ShieldCheck size={14}/> Acesso exclusivo para policiais e administradores autorizados.</small></>}</div></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
