import {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Loader2,LogIn,ShieldCheck} from 'lucide-react';
import type {Session} from '@supabase/supabase-js';
import {initialize,supabase,loginIdentity,configureAdministrator} from './lib/api';
import Platform from './platform';
import './styles.css';
function App(){
 const [loading,setLoading]=useState(true),[configured,setConfigured]=useState(false),[session,setSession]=useState<Session|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[setupToken]=useState(()=>new URLSearchParams(location.hash.slice(1)).get('setup')||''),[mode,setMode]=useState<'login'|'signup'|'recover'|'password'|'setup'>(setupToken?'setup':'login'),[email,setEmail]=useState(''),[password,setPassword]=useState('');
 useEffect(()=>{let alive=true,unsubscribe:(()=>void)|undefined;const recovery=new URLSearchParams(location.hash.slice(1)).get('type')==='recovery';if(recovery)setMode('password');initialize().then(async client=>{if(!alive)return;const {data:listener}=client.auth.onAuthStateChange((event,current)=>{if(!alive)return;setSession(current);if(event==='PASSWORD_RECOVERY')setMode('password')});unsubscribe=()=>listener.subscription.unsubscribe();const {data}=await client.auth.getSession();if(!alive)return;setSession(data.session);setConfigured(true);}).catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false;unsubscribe?.()}},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{let result;if(mode==='setup'){await configureAdministrator(setupToken,password);history.replaceState(null,'',location.pathname);setMode('login');result=await supabase().auth.signInWithPassword({email:loginIdentity('4º Pelotão'),password});}else if(mode==='login')result=await supabase().auth.signInWithPassword({email:loginIdentity(email),password});else if(mode==='signup')result=await supabase().auth.signUp({email,password,options:{emailRedirectTo:location.origin+import.meta.env.BASE_URL}});else if(mode==='recover')result=await supabase().auth.resetPasswordForEmail(email,{redirectTo:location.origin+import.meta.env.BASE_URL});else result=await supabase().auth.updateUser({password});if(result.error)throw result.error;if(mode==='signup'){setMessage('Confira seu e-mail para confirmar o cadastro. O acesso aos materiais depende da autorização do comando.');setPassword('')}if(mode==='recover')setMessage('Se o endereço puder receber a recuperação, você receberá um link por e-mail.');if(mode==='password'){setMessage('Senha atualizada.');setPassword('');setMode('login')}}catch(e){const msg=(e as Error).message;setError(msg==='Invalid login credentials'?'E-mail ou senha inválidos.':msg==='Email not confirmed'?'Confirme seu e-mail antes de entrar.':msg.includes('rate limit')?'Limite de tentativas atingido. Aguarde e tente novamente.':msg)}finally{setBusy(false)}}
 if(session&&mode!=='password'&&mode!=='setup')return <Platform/>;
 return <div className="entry-screen"><div className="entry-card"><img src={import.meta.env.BASE_URL+'brasao.png'} alt="Brasão do 4º Pelotão"/><p className="eyebrow">POLÍCIA MILITAR DA BAHIA · 80ª CIPM</p><h1>Gestão operacional<br/>4º Pelotão</h1><p>Conferência de serviço, inventários e cautelas de Condeúba, Cordeiros e Mortugaba.</p>{loading?<p className="loading"><Loader2 className="spin"/> Preparando acesso…</p>:<>{error&&<p className="auth-error" role="alert">{error}</p>}{message&&<p className="auth-message" role="status">{message}</p>}{configured&&<form className="auth-form" onSubmit={submit}><h2>{mode==='login'?'Acesso individual':mode==='signup'?'Criar conta':mode==='recover'?'Recuperar senha':mode==='setup'?'Definir senha do 4º Pelotão':'Definir nova senha'}</h2>{mode==='setup'&&<p>Login administrativo: <strong>4º Pelotão</strong>. Defina uma senha de pelo menos 12 caracteres.</p>}{mode!=='password'&&mode!=='setup'&&<label className="field">{mode==='login'?'Login ou e-mail autorizado':'E-mail autorizado'}<input type={mode==='login'?'text':'email'} required autoComplete={mode==='login'?'username':'email'} value={email} onChange={e=>setEmail(e.target.value)}/></label>}{mode!=='recover'&&<label className="field">{mode==='password'?'Nova senha':'Senha'}<input required type="password" minLength={mode==='login'?1:12} autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label>}<button className="btn primary" disabled={busy}>{busy?<Loader2 size={17} className="spin"/>:<LogIn size={17}/>} {mode==='login'?'Entrar':mode==='signup'?'Cadastrar conta':mode==='recover'?'Enviar recuperação':mode==='setup'?'Definir senha e entrar':'Atualizar senha'}</button>{mode==='login'?<div className="auth-links"><button type="button" onClick={()=>{setMode('signup');setError('');setMessage('')}}>Primeiro acesso</button><button type="button" onClick={()=>{setMode('recover');setError('');setMessage('')}}>Esqueci minha senha</button></div>:mode!=='password'&&mode!=='setup'&&<button type="button" className="text-link" onClick={()=>{setMode('login');setError('');setMessage('')}}>Voltar ao acesso</button>}</form>}<small><ShieldCheck size={14}/> Acesso exclusivo para policiais e administradores autorizados.</small></>}</div></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
