import {actor,admin,stmt,db,UserError,textValue,integer,auditStmt,guard,clearGuard,ownerId,mutableUser,generalOfficer,allow,operate,general,manageOfficer,readRecord,authAdmin} from './server.ts';
import {changePassword,initialPassword} from './credentials.ts';
import {extraAction} from './extras.ts';
import {accountAction} from './accounts.ts';
import {loadAction,personalLoads,report,stockQuery} from './loads.ts';
import {CITIES,PLATOONS,platoonOf,CONDITIONS,localDay,needsJustification,type Item,type Officer,type Entry} from './domain.ts';

const city=(v:unknown)=>{if(!CITIES.includes(v as any))throw new UserError('Selecione um município válido.');return String(v);};
const json=(v:unknown,status=200)=>Response.json(v,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
function error(e:unknown){console.error(e instanceof Error?e.message:e);if((e as any)?.code==='42501')return json({error:'Operação fora das permissões do pelotão.'},403);if(e instanceof UserError)return json({error:e.message},e.status);const s=String(e);if(s.includes('operation_valid'))return json({error:'O registro foi alterado por outro usuário. Atualize os dados e revise novamente.'},409);if((e as any)?.constraint_name?.startsWith('checks_'))return json({error:'Já existe uma conferência deste dia para o município ou responsável.'},409);if((e as any)?.constraint_name?.startsWith('loads_'))return json({error:'Você já registrou sua única carga de hoje.'},409);if(s.includes('UNIQUE')||(e as any)?.code==='23505')return json({error:'Já existe um cadastro com esta matrícula, e-mail ou identificação.'},409);return json({error:'Não foi possível concluir a operação. Os dados preenchidos foram preservados.'},503);}
export async function GET(req:Request){try{
 const a=await actor(req,true);return await db().asActor(a.id,async()=>{
 if(a.must_change_password)return json({user:a,passwordChangeRequired:true});if(a.approval_pending)return json({user:a,approvalPending:true});
 const u=new URL(req.url);if(u.searchParams.has('report'))return json(await report(a,u.searchParams.get('report')!));
 const selected=u.searchParams.get('city')?city(u.searchParams.get('city')):PLATOONS.find(p=>p.id===a.home_platoon)?.cities.find(c=>a.cities?.includes(c))||a.cities?.[0];if(!selected)throw new UserError('Não há vínculos operacionais ativos. Procure o gestor geral.',403);if(a.role==='policial'||!a.managementCities?.includes(selected))operate(a,selected);
 const rootId=await ownerId(),globalId=await generalOfficer();const isAdmin=a.role!=='policial';const scope=new Set(isAdmin?[...(a.managementCities||[]),selected]:[selected]);
 const [items,officers,categories,allChecks,movements,alerts,audit,memberships,corrections]=await Promise.all([stmt(stockQuery+' ORDER BY i.category,i.name,i.serial').all<any>(),stmt('SELECT * FROM officers ORDER BY city,rank,name').all<any>(),stmt('SELECT * FROM categories ORDER BY name').all<any>(),stmt('SELECT * FROM checks ORDER BY created_at DESC').all<any>(),stmt('SELECT * FROM movements ORDER BY withdrawn_at DESC').all<any>(),stmt('SELECT * FROM alerts ORDER BY created_at DESC').all<any>(),stmt('SELECT * FROM audit ORDER BY created_at DESC LIMIT 1000').all<any>(),stmt('SELECT * FROM officer_platoons WHERE active=1').all<any>(),stmt('SELECT * FROM check_corrections ORDER BY created_at').all<any>()]);
 const own=(c:any)=>c.actor===a.id||a.officer_id&&JSON.parse(c.crew).includes(a.officer_id);const visibleChecks=allChecks.results.filter(c=>a.is_global||isAdmin&&a.managementCities?.includes(c.city)||own(c)&&!c.deleted_at);const ids=new Set(visibleChecks.map(c=>c.id));
 const people=officers.results.filter(o=>a.is_global||isAdmin&&o.home_platoon===a.home_platoon||o.active&&!o.deleted_at&&(o.id===globalId||memberships.results.some(m=>m.officer_id===o.id&&a.cities?.some(c=>platoonOf(c)===m.platoon_id)))).map(o=>{const row={...o,platoons:memberships.results.filter(m=>m.officer_id===o.id).map(m=>m.platoon_id),protected:o.id===globalId||o.auth_user_id===rootId,role:o.id===globalId?'gestor_geral':o.role};if(!isAdmin){delete row.email;delete row.auth_user_id;delete row.permissions;delete row.deletion_reason;}return row});
 const boardCities=a.capabilities?.global_status?CITIES:isAdmin?a.managementCities||[]:[];const today=localDay();const start=u.searchParams.get('start')||today,end=u.searchParams.get('end')||today;if(!/^\d{4}-\d{2}-\d{2}$/.test(start)||!/^\d{4}-\d{2}-\d{2}$/.test(end)||start>end)throw new UserError('Período inválido.');
 const dashboard=boardCities.map(c=>{const checks=allChecks.results.filter(x=>x.city===c&&!x.deleted_at);const latest=checks.find(x=>x.status==='finalizada');const current=checks.find(x=>x.service_day>=start&&x.service_day<=end&&x.status==='finalizada');const draft=checks.find(x=>x.service_day>=start&&x.service_day<=end&&x.status==='rascunho');const pending=alerts.results.filter(x=>x.city===c&&x.status==='aberta');const activeLoads=([] as any[]);const entries=current?JSON.parse(current.entries):[];return {city:c,platoon_id:platoonOf(c),status:pending.length||current&&entries.some((e:any)=>needsJustification(e,e.expected||0))?'divergencia':current?'conferida':draft?'andamento':'pendente',last_at:latest?.finalized_at||null,responsible:current?.actor_name||latest?.actor_name||'',crew:current?JSON.parse(current.crew_labels||'[]'):[],checked:entries.length,missing:entries.filter((e:any)=>e.condition==='Não encontrado').length,divergences:entries.filter((e:any)=>needsJustification(e,e.expected||0)).length,pending:pending.length,in_progress:!!draft,last_movements:movements.results.filter(m=>m.origin===c||m.destination===c).slice(0,3).map(m=>({at:m.withdrawn_at,status:m.status,quantity:m.quantity,origin:m.origin,destination:m.destination})),activeLoads};});
 const loadRows=await stmt("SELECT city,COUNT(*)::int AS total,COALESCE(SUM((SELECT SUM((e->>'quantity')::integer) FROM jsonb_array_elements(entries::jsonb) e)),0)::int AS quantity FROM loads WHERE status='ativa' GROUP BY city").all<any>();dashboard.forEach(d=>{const l=loadRows.results.find(l=>l.city===d.city);Object.assign(d,{loads:l?.total||0,loaded_quantity:l?.quantity||0});});
 return json({user:a,period:{start,end},selectedCity:selected,platoons:PLATOONS,cities:a.cities,dashboard,loads:await personalLoads(a),items:items.results.filter(i=>a.is_global||scope.has(i.location)||isAdmin&&a.managementCities?.includes(i.city)).map(i=>({...i,reserved:Number(i.reserved),available:Math.max(0,i.quantity-Number(i.reserved))})),primaryAccount:a.is_global?{id:rootId,name:'4º Pelotão',protected:true}:undefined,officers:people,categories:categories.results,checks:visibleChecks.map(c=>({...c,corrections:corrections.results.filter(x=>x.check_id===c.id),entries:JSON.parse(c.entries),crew:JSON.parse(c.crew),crew_labels:JSON.parse(c.crew_labels||'[]')})),movements:movements.results.filter(m=>a.is_global||m.officer_id===a.officer_id||isAdmin&&a.managementCities?.some(c=>c===m.origin||c===m.destination)),alerts:alerts.results.filter(x=>a.is_global||isAdmin&&a.managementCities?.includes(x.city)||ids.has(x.check_id)&&allChecks.results.some(c=>c.id===x.check_id&&c.actor===a.id)),audit:a.is_global?audit.results.slice(0,300):audit.results.filter(x=>a.capabilities?.audit&&x.platoon_id===a.home_platoon||x.actor===a.id).slice(0,300),serverTime:new Date().toISOString()});
 });
}catch(e){return error(e);}}
export async function POST(req:Request){try{
 const origin=req.headers.get('origin');if(origin&&![Deno.env.get('APP_ORIGIN')||'https://rapha11novais-source.github.io','https://gestao-pelotoes.github.io'].includes(origin))throw new UserError('Origem da solicitação inválida.',403);
 if(Number(req.headers.get('content-length')||0)>300000)throw new UserError('Solicitação muito grande.',413);
 const a=await actor(req,true);return await db().asActor(a.id,async()=>{const b=await req.json() as any;const now=new Date().toISOString();const action=b.action;if(action==='change-own-password')return json(await changePassword(a,b,now));if(a.approval_pending)throw new UserError('Seu cadastro aguarda validação pelo gestor.',403);if(a.must_change_password)throw new UserError('Altere sua senha temporária antes de acessar os materiais.',403);const extraScope=await extraAction(a,b,now);if(extraScope)return json(extraScope);const account=await accountAction(a,b,now);if(account)return json(account);const extra=await loadAction(a,b,now);if(extra)return json(extra);const id=textValue(b.id,100)||crypto.randomUUID();
 if(action==='save-check'){
  if(b.commander!==true)throw new UserError('A conferência deve ser realizada pelo comandante da guarnição.');const day=localDay(new Date(now));
  if(!a.officer_id)throw new UserError('Vincule seu acesso a um cadastro policial em Efetivo antes de conferir.');
  const selected=city(b.city);operate(a,selected);const crew=[...new Set<string>((Array.isArray(b.crew)?b.crew:[]).filter((x:any)=>typeof x==='string'))];
  if(!crew.includes(a.officer_id))crew.unshift(a.officer_id);
  if(crew.length>100)throw new UserError('Guarnição inválida.');
  const crewRows=await stmt(`SELECT id,name,registration FROM officers WHERE active=1 AND validated=1 AND deleted_at IS NULL AND id IN (${crew.map(()=>'?').join(',')})`,...crew).all<any>();const linked=await stmt(`SELECT officer_id FROM officer_platoons WHERE active=1 AND platoon_id=? AND officer_id IN (${crew.map(()=>'?').join(',')})`,platoonOf(selected),...crew).all<any>();const generalMember=await generalOfficer();if(crew.some(id=>id!==generalMember&&!(a.is_global&&id===a.officer_id)&&!linked.results.some(m=>m.officer_id===id)))throw new UserError('Há policial sem vínculo ativo com o pelotão deste serviço.');if(crewRows.results.length!==crew.length)throw new UserError('Há policial inativo ou pendente de validação na guarnição.');
  const old=await stmt('SELECT * FROM checks WHERE id=?',id).first<any>();
  if(old&&(old.deleted_at||old.actor!==a.id||old.status!=='rascunho'))throw new UserError('Este registro já foi finalizado ou pertence a outro policial.',403);
  if(old&&old.service_day!==day)throw new UserError('Este rascunho pertence a outro dia. Inicie a conferência de hoje.');
  if(await stmt('SELECT id FROM checks WHERE (actor=? OR officer_id=?) AND service_day=? AND deleted_at IS NULL AND id<>?',a.id,a.officer_id,day,id).first())throw new UserError('Você já possui uma conferência de hoje. Retome seu registro.',409);
  if(b.finalize===true&&await stmt("SELECT id FROM checks WHERE city=? AND service_day=? AND status='finalizada' AND deleted_at IS NULL AND id<>?",selected,day,id).first())throw new UserError('Este município já possui a conferência de hoje.',409);
  const {results:current}=await stmt('SELECT * FROM inventory WHERE location=? AND quantity>0 AND deleted_at IS NULL ORDER BY id',selected).all<Item>();
  const incoming:Array<Entry>=Array.isArray(b.entries)?b.entries:[];const final=b.finalize===true;
  if(!current.length)throw new UserError('Não há materiais cadastrados para este município.');
  if(final&&(incoming.length!==current.length||new Set(incoming.map(e=>e.id)).size!==current.length))throw new UserError('Confira todos os materiais antes de finalizar.');
  const entries=current.map(i=>{
   const e=incoming.find(e=>e.id===i.id);const quantity=e?.quantity==null?null:integer(e.quantity,0,i.serial?1:1000000);const condition=textValue(e?.condition,40);const notes=textValue(e?.notes);const identification=e?.identification===true;
   if(final&&(!e||e.version!==i.version))throw new UserError('O inventário mudou durante a conferência. Reabra a conferência e revise os valores.',409);
   if(final&&(quantity===null||!CONDITIONS.includes(condition as any)))throw new UserError('Informe quantidade e condição de todos os materiais.');
   if(final&&condition==='Não encontrado'&&quantity!==0)throw new UserError('Material não encontrado deve ter quantidade conferida igual a zero.');
   if(final&&quantity===0&&condition!=='Não encontrado')throw new UserError('Selecione Não encontrado para materiais com quantidade zero.');
   const entry={id:i.id,quantity,condition,notes,identification,expected:i.quantity,version:i.version,name:i.name,serial:i.serial,category:i.category,city:i.city,location:i.location};
   if(final&&needsJustification(entry,i.quantity)&&notes.length<3)throw new UserError('Inclua uma justificativa para cada divergência, ausência ou condição ruim.');
   return entry;
  });
  const statements:any[]=[];const gid=crypto.randomUUID();
  if(old)statements.push(guard(gid,'SELECT COUNT(*)=1 FROM checks WHERE id=? AND actor=? AND status=? AND updated_at=?',id,a.id,'rascunho',old.updated_at));
  else statements.push(guard(gid,'SELECT COUNT(*)=0 FROM checks WHERE id=?',id));
  if(final){statements.push(guard(gid+'-count','SELECT COUNT(*)=? FROM inventory WHERE location=? AND quantity>0 AND deleted_at IS NULL',entries.length,selected));entries.forEach((e,idx)=>statements.push(guard(gid+'-'+idx,'SELECT COUNT(*)=1 FROM inventory WHERE id=? AND version=? AND location=? AND quantity=?',e.id,e.version,selected,e.expected)));}
  statements.push(stmt('INSERT INTO checks(id,city,actor,officer_id,actor_name,crew,crew_labels,entries,notes,status,created_at,updated_at,finalized_at,service_day) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET city=excluded.city,crew=excluded.crew,crew_labels=excluded.crew_labels,entries=excluded.entries,notes=excluded.notes,status=excluded.status,updated_at=excluded.updated_at,finalized_at=excluded.finalized_at',id,selected,a.id,a.officer_id,a.name,JSON.stringify(crew),JSON.stringify(crew.map(id=>{const o=crewRows.results.find(o=>o.id===id);return o.name+' ('+o.registration+')'})),JSON.stringify(entries),textValue(b.notes),final?'finalizada':'rascunho',old?.created_at||now,now,final?now:null,day));
  if(final)entries.forEach(e=>{
   statements.push(stmt('UPDATE inventory SET condition=? WHERE id=?',e.condition,e.id));
   if(needsJustification(e,e.expected!))statements.push(stmt('INSERT INTO alerts(id,check_id,item_id,city,title,detail,status,created_at) VALUES(?,?,?,?,?,?,?,?)',crypto.randomUUID(),id,e.id,selected,e.condition==='Não encontrado'?'Material não encontrado':e.identification?'Identificação divergente':e.condition==='Ruim'?'Equipamento em estado ruim':'Divergência quantitativa',`${e.name}${e.serial?' · '+e.serial:''}. Previsto: ${e.expected}; conferido: ${e.quantity}. ${e.notes}`,'aberta',now));
  });
  statements.push(auditStmt(a,final?'Conferência finalizada':'Rascunho salvo',id,old,{city:selected,crew,entries},now),clearGuard(gid));
  if(final){entries.forEach((_,idx)=>statements.push(clearGuard(gid+'-'+idx)));statements.push(clearGuard(gid+'-count'));}
  await db().batch(statements);return json({ok:true,id});
 }
 admin(a);
 if(action==='save-item'){
  const old=await stmt('SELECT * FROM inventory WHERE id=?',id).first<Item>();const name=textValue(b.name,150);const cat=await stmt('SELECT * FROM categories WHERE id=?',textValue(b.category,100)).first<any>();if(!name||!cat)throw new UserError('Preencha nome e categoria.');
  if(old){allow(a,'materials',old.city);allow(a,'materials',old.location);if(old.deleted_at)throw new UserError('Restaure o material antes de editar.');}
  const quantity=integer(b.quantity);const serial=textValue(b.serial,100)||null;if((cat.mode==='individual'||!old&&['armas','coletes','placas','capas'].includes(cat.id))&&(!serial||quantity!==1))throw new UserError('Itens individuais exigem identificação e quantidade 1.');
  const selected=city(b.city);const location=city(b.location||selected);allow(a,'materials',selected);allow(a,'materials',location);const condition=textValue(b.condition,40)||'A conferir';if(![...CONDITIONS,'A conferir'].includes(condition as any))throw new UserError('Condição inválida.');
  if(old){const active=await stmt("SELECT id FROM movements WHERE item_id=? AND status!='devolvida'",id).first();if(active)throw new UserError('Regularize a cautela deste material antes de editar.');if(b.version!==old.version)throw new UserError('O material mudou. Atualize e tente novamente.',409);}
  if(old&&quantity!==old.quantity&&!textValue(b.reason))throw new UserError('Justifique a alteração do quantitativo previsto.');
  if(cat.id==='municoes'&&!textValue(b.caliber))throw new UserError('Informe o calibre das munições.');
  const next={id,name,category:cat.id,serial,manufacturer:textValue(b.manufacturer,100)||null,model:textValue(b.model,100)||null,caliber:textValue(b.caliber,40)||null,city:selected,location,quantity,condition,notes:textValue(b.notes),source:old?.source||'Cadastro administrativo',version:(old?.version||0)+1};
  const gid=crypto.randomUUID();const ops:any[]=[guard(gid,old?'SELECT COUNT(*)=1 FROM inventory WHERE id=? AND version=?':'SELECT COUNT(*)=0 FROM inventory WHERE id=?',id,...(old?[old.version]:[]))];
  ops.push(stmt('INSERT INTO inventory(id,name,category,serial,manufacturer,model,caliber,city,location,quantity,condition,notes,source,version) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,category=excluded.category,serial=excluded.serial,manufacturer=excluded.manufacturer,model=excluded.model,caliber=excluded.caliber,city=excluded.city,location=excluded.location,quantity=excluded.quantity,condition=excluded.condition,notes=excluded.notes,version=excluded.version',...Object.values(next)),auditStmt(a,'Material atualizado',id,old,{...next,reason:textValue(b.reason)},now),clearGuard(gid));await db().transaction(async tx=>{await tx.prepare('SELECT id FROM inventory WHERE id=? FOR UPDATE').bind(id).first();const live=await tx.prepare("SELECT li.load_id FROM load_items li JOIN loads l ON l.id=li.load_id WHERE li.item_id=? AND l.status='ativa'").bind(id).first();if(live)throw new UserError('O material possui carga ativa. Registre a devolução antes de editar.');await tx.batch(ops)});return json({ok:true});
 }
 if(action==='save-officer'){
  await mutableUser(id);const old=await stmt('SELECT * FROM officers WHERE id=?',id).first<Officer>();if(old?.deleted_at)throw new UserError('Restaure o cadastro antes de editar.');if(old)await manageOfficer(a,old);const name=textValue(b.name,150),rank=textValue(b.rank,40),callsign=textValue(b.callsign,80),registration=textValue(b.registration,30);if(!name||!rank||!/^\d{5,12}$/.test(registration))throw new UserError('Preencha nome, graduação, nome de guerra e matrícula numérica.');
  if(old?.auth_user_id&&old.validated&&old.registration!==registration)throw new UserError('A matrícula de um acesso já validado não pode ser alterada.');if(await stmt('SELECT id FROM officers WHERE registration=? AND id<>?',registration,id).first())throw new UserError('Matrícula já cadastrada.',409);
  const role=textValue(b.role,40);if(!['policial','administrador','comando','comandante','subcomandante'].includes(role))throw new UserError('Perfil inválido.');
  const home=textValue(b.home_platoon,10)||old?.home_platoon||a.home_platoon||'p4';if(!PLATOONS.some(p=>p.id===home))throw new UserError('Pelotão inválido.');const staffCity=city(b.city);if(platoonOf(staffCity)!==home)throw new UserError('A lotação habitual deve pertencer ao pelotão de origem.');allow(a,'officers',staffCity);if(!a.is_global&&(role!==(old?.role||'policial')||home!==(old?.home_platoon||a.home_platoon)))throw new UserError('Somente o gestor geral pode alterar perfil e pelotão de origem.',403);
  const permissions=b.permissions??old?.permissions??{};if(typeof permissions!=='object'||Array.isArray(permissions)||Object.keys(permissions).some(k=>!['materials','officers','movements','audit','global_status'].includes(k)||typeof permissions[k]!=='boolean'))throw new UserError('Permissões inválidas.');if(!a.is_global&&JSON.stringify(permissions)!==JSON.stringify(old?.permissions||{}))throw new UserError('Permissões adicionais exigem gestor geral.',403);
  const email=textValue(b.email,200).toLowerCase()||null;if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new UserError('Informe um e-mail válido.');
  if(old?.id===a.officer_id&&(role==='policial'||!b.active||!b.validated))throw new UserError('Seu próprio acesso de comando deve permanecer autorizado.');
  const temporaryIdentityChange=old?.auth_user_id&&(!old.validated||old.must_change_password)&&(old.registration!==registration||initialPassword(old)!==initialPassword({name,registration}));if(temporaryIdentityChange){const {error}=await authAdmin().auth.admin.updateUserById(old.auth_user_id,{email:registration+'@accounts.invalid',email_confirm:true,password:initialPassword({name,registration}),user_metadata:{full_name:name}});if(error)throw new UserError('Não foi possível corrigir o acesso inicial.',503);await stmt('UPDATE officers SET must_change_password=true WHERE id=?',id).run();}
  const next={id,name,rank,callsign,registration,city:city(b.city),role,email,active:b.active?1:0,validated:b.validated?1:0};
  await db().batch([stmt('INSERT INTO officers(id,name,rank,callsign,registration,city,role,email,active,validated,home_platoon,permissions) VALUES(?,?,?,?,?,?,?,?,?,?,?,?::jsonb) ON CONFLICT(id) DO UPDATE SET name=excluded.name,rank=excluded.rank,callsign=excluded.callsign,registration=excluded.registration,city=excluded.city,role=excluded.role,email=excluded.email,active=excluded.active,validated=excluded.validated,home_platoon=excluded.home_platoon,permissions=excluded.permissions',...Object.values(next),home,JSON.stringify(permissions)),...(!old||old.home_platoon!==home?[stmt('INSERT INTO officer_platoons(officer_id,platoon_id,active) VALUES(?,?,1) ON CONFLICT(officer_id,platoon_id) DO UPDATE SET active=1',id,home)]:[]),auditStmt(a,'Cadastro policial atualizado',id,old,{...next,home_platoon:home,permissions},now)]);return json({ok:true,id});
 }
 if(action==='bind-self'){general(a);
  const officer=await stmt('SELECT * FROM officers WHERE id=? AND active=1 AND validated=1 AND deleted_at IS NULL',textValue(b.officerId)).first<Officer>();if(!officer)throw new UserError('Escolha um cadastro ativo e validado.');if(officer.role==='policial')throw new UserError('O gestor inicial deve vincular um perfil administrativo.');
  if(!a.is_owner&&officer.auth_user_id&&officer.auth_user_id!==a.id)throw new UserError('Este cadastro já possui outro acesso.');
  if(officer.email&&officer.email.toLowerCase()!==a.email.toLowerCase())throw new UserError('Este cadastro já está vinculado a outro e-mail.');
  await db().batch([...(!a.is_owner?[stmt('UPDATE officers SET auth_user_id=? WHERE id=?',a.id,officer.id)]:[]),stmt('UPDATE principals SET officer_id=?,role=?,name=? WHERE id=?',officer.id,a.is_owner?'comando':officer.role,a.is_owner?'4º Pelotão':officer.name,a.id),auditStmt(a,'Acesso vinculado ao cadastro',officer.id,a,{officerId:officer.id,email:a.email},now)]);return json({ok:true});
 }
 if(action==='save-category'){general(a);
  const name=textValue(b.name,80),mode=textValue(b.mode);if(!name||!['individual','quantidade'].includes(mode))throw new UserError('Informe nome e tipo de controle.');await db().batch([stmt('INSERT INTO categories(id,name,mode) VALUES(?,?,?)',id,name,mode),auditStmt(a,'Categoria criada',id,null,{name,mode},now)]);return json({ok:true});
 }
 if(action==='resolve-alert'){
  const resolution=textValue(b.resolution);if(resolution.length<3)throw new UserError('Registre a providência adotada.');const old=await stmt("SELECT * FROM alerts WHERE id=? AND status='aberta'",id).first();if(!old)throw new UserError('A ocorrência já está resolvida ou não existe.');allow(a,'materials',(old as any).city);await db().batch([stmt("UPDATE alerts SET status='resolvida',resolution=?,resolved_at=?,resolved_by=? WHERE id=? AND status='aberta'",resolution,now,a.name,id),auditStmt(a,'Ocorrência regularizada',id,old,{resolution},now)]);return json({ok:true});
 }
 if(action==='create-movement'){
  const i=await stmt('SELECT * FROM inventory WHERE id=?',textValue(b.itemId)).first<Item>();const o=await stmt('SELECT * FROM officers WHERE id=? AND active=1 AND validated=1 AND deleted_at IS NULL',textValue(b.officerId)).first<Officer>();if(!i||!o)throw new UserError('Selecione material e policial ativo e validado.');
  if(i.deleted_at)throw new UserError('Material excluído.');allow(a,'movements',i.city);allow(a,'movements',i.location);const quantity=integer(b.quantity,1,i.quantity);const active=await stmt("SELECT id FROM movements WHERE item_id=? AND status!='devolvida'",i.id).first();if(active)throw new UserError('Já existe cautela aberta para este registro.');const destination=city(b.destination);allow(a,'movements',destination);const link=await stmt('SELECT officer_id FROM officer_platoons WHERE officer_id=? AND platoon_id=? AND active=1',o.id,platoonOf(destination)).first();if(!link&&o.id!==await generalOfficer()&&o.auth_user_id!==await ownerId())throw new UserError('O responsável não possui vínculo com o pelotão de destino.');const due=textValue(b.dueAt,50)||null;if(due&&(!Number.isFinite(Date.parse(due))||Date.parse(due)<Date.now()))throw new UserError('A devolução prevista deve ser futura.');const notes=textValue(b.notes);if(!notes)throw new UserError('Informe a finalidade da cautela.');
  const gid=crypto.randomUUID();await db().transaction(async tx=>{await tx.prepare('SELECT id FROM inventory WHERE id=? FOR UPDATE').bind(i.id).first();const fresh=await tx.prepare(stockQuery+' WHERE i.id=?').bind(i.id).first<any>();if(!fresh||quantity>fresh.quantity-Number(fresh.reserved))throw new UserError('Quantidade insuficiente após considerar cargas e cautelas ativas.',409);await tx.batch([guard(gid,"SELECT COUNT(*)=0 FROM movements WHERE item_id=? AND status!='devolvida'",i.id),stmt('INSERT INTO movements(id,item_id,item_name,officer_id,origin,destination,quantity,withdrawn_at,due_at,status,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',id,i.id,i.name+(i.serial?' · '+i.serial:''),o.id,i.location,destination,quantity,now,due,'aguardando',notes,a.name),auditStmt(a,'Cautela registrada',id,null,{item:i.id,officer:o.id,origin:i.location,destination,quantity,dueAt:due,notes},now),clearGuard(gid)]);});return json({ok:true});
 }
 if(action==='receive-movement'||action==='return-movement'){
  const m=await stmt('SELECT * FROM movements WHERE id=?',id).first<any>();if(!m)throw new UserError('Cautela não encontrada.');allow(a,'movements',m.origin);allow(a,'movements',m.destination);const receiving=action==='receive-movement';if(m.status!==(receiving?'aguardando':'recebida'))throw new UserError('A cautela não está disponível para esta operação.');
  const i=await stmt('SELECT * FROM inventory WHERE id=?',m.item_id).first<Item>();if(!i)throw new UserError('Material não encontrado.');allow(a,'movements',i.city);const gid=crypto.randomUUID();const ops:any[]=[guard(gid,'SELECT COUNT(*)=1 FROM movements WHERE id=? AND status=?',id,m.status)];
  if(receiving){
   ops.push(guard(gid+'-stock','SELECT COUNT(*)=1 FROM inventory WHERE id=? AND quantity>=? AND version=?',i.id,m.quantity,i.version));
   if(m.quantity===i.quantity)ops.push(stmt('UPDATE inventory SET location=?,version=version+1 WHERE id=?',m.destination,i.id));
   else {ops.push(stmt('UPDATE inventory SET quantity=quantity-?,version=version+1 WHERE id=?',m.quantity,i.id),stmt('INSERT INTO inventory(id,name,category,serial,manufacturer,model,caliber,city,location,quantity,condition,notes,source,version) SELECT ?,name,category,NULL,manufacturer,model,caliber,city,?,?,condition,notes,source,1 FROM inventory WHERE id=?','lote-'+id,m.destination,m.quantity,i.id));}
   ops.push(stmt("UPDATE movements SET status='recebida',received_at=? WHERE id=?",now,id),clearGuard(gid+'-stock'));
  }else{
   const lot=await stmt('SELECT * FROM inventory WHERE id=?','lote-'+id).first<Item>();
   if(lot){const other=await stmt("SELECT id FROM movements WHERE item_id=? AND status!='devolvida'",lot.id).first();if(other)throw new UserError('Há outra cautela em andamento para o lote recebido.');ops.push(guard(gid+'-lot','SELECT COUNT(*)=1 FROM inventory WHERE id=? AND quantity=? AND version=?',lot.id,m.quantity,lot.version),stmt('UPDATE inventory SET quantity=quantity+?,version=version+1 WHERE id=?',m.quantity,i.id),stmt('DELETE FROM inventory WHERE id=?',lot.id),clearGuard(gid+'-lot'));}
   else ops.push(stmt('UPDATE inventory SET location=?,version=version+1 WHERE id=?',m.origin,i.id));
   ops.push(stmt("UPDATE movements SET status='devolvida',returned_at=? WHERE id=?",now,id));
  }
  ops.push(auditStmt(a,receiving?'Recebimento confirmado':'Devolução confirmada',id,m,{status:receiving?'recebida':'devolvida'},now),clearGuard(gid));await db().batch(ops);return json({ok:true});
 }
 throw new UserError('Operação não reconhecida.');
 });
}catch(e){return error(e);}}
