import {createClient} from 'npm:@supabase/supabase-js@2.117.3';
import {CITIES,PLATOONS,platoonOf} from './domain.ts';
import {database} from './db.ts';
export class UserError extends Error {constructor(message:string,public status=400){super(message);}}
export const db=()=>database;
export const stmt=(query:string,...args:unknown[])=>db().prepare(query).bind(...args);
export type Actor={id:string;officer_id:string|null;role:string;email:string;name:string;is_owner?:boolean;is_global?:boolean;registration?:string;home_platoon?:string;cities?:string[];managementCities?:string[];permissions?:Record<string,boolean>;capabilities?:Record<string,boolean>;must_change_password?:boolean;approval_pending?:boolean};
async function verifiedUser(req:Request){const token=req.headers.get('Authorization')?.match(/^Bearer (.+)$/i)?.[1];if(!token)throw new UserError('Entre com sua conta para continuar.',401);const keys=JSON.parse(Deno.env.get('SUPABASE_PUBLISHABLE_KEYS')||'{}');const key=keys.default||Deno.env.get('SUPABASE_ANON_KEY');const url=Deno.env.get('SUPABASE_URL');if(!url||!key)throw new UserError('O serviço de autenticação está indisponível.',503);const client=createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});const {data,error}=await client.auth.getUser(token);if(error||!data.user?.email||!data.user.email_confirmed_at)throw new UserError('A sessão é inválida ou o e-mail ainda não foi confirmado.',401);return data.user;}
export async function actor(req:Request,allowPending=false):Promise<Actor>{
 const user=await verifiedUser(req);const email=user.email!.toLowerCase();const uid=user.id;const name=user.user_metadata?.full_name||email;
 let p=await stmt('SELECT * FROM principals WHERE id=?',uid).first<Actor>();
 const settings=await stmt('SELECT value FROM settings WHERE key=?','owner_email').first<{value:string}>();
 const owner=(settings?.value||'').trim().toLowerCase();
 if(!p&&owner&&email===owner){const created=await stmt("INSERT OR IGNORE INTO principals(id,officer_id,role,email,name) VALUES(?,NULL,'comando',?,?)",uid,email,name).run();if(created.meta.changes)await auditStmt({id:uid,officer_id:null,role:'comando',email,name},'Acesso inicial autorizado',uid,null,{role:'comando',militaryIdentityLinked:false}).run();p=await stmt('SELECT * FROM principals WHERE id=?',uid).first<Actor>();}
 if(uid===await ownerId()&&p)return enrich({...p,role:'gestor_geral',name:'4º Pelotão',is_owner:true},p.officer_id?await stmt('SELECT * FROM officers WHERE id=?',p.officer_id).first():null);
 const o=await stmt('SELECT * FROM officers WHERE auth_user_id=? OR (auth_user_id IS NULL AND lower(email)=?)',uid,email).first<any>();
 if(o){if(o.deleted_at||!o.active||!o.validated&&!allowPending)throw new UserError('Seu cadastro precisa de autorização ou está inativo. Procure o gestor.',403);await stmt('INSERT INTO principals(id,officer_id,role,email,name) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET officer_id=excluded.officer_id,role=excluded.role,email=excluded.email,name=excluded.name',uid,o.id,o.role,email,o.name).run();return enrich({id:uid,officer_id:o.id,role:o.role,email,name:o.name,approval_pending:!o.validated},o);}
 if(p?.officer_id)throw new UserError('Seu cadastro precisa de autorização ou está inativo. Procure o comando.',403);
 if(!p)throw new UserError('Seu e-mail ainda não foi autorizado pelo comando.',403);
 throw new UserError('O acesso precisa de vínculo policial autorizado. Procure o gestor geral.',403);
}
export function admin(a:Actor){if(a.role==='policial')throw new UserError('Esta operação exige autorização administrativa.',403);}
export function manager(a:Actor){admin(a);}
export function general(a:Actor){if(!a.is_global)throw new UserError('Somente os gestores gerais podem alterar permissões e vínculos.',403);}
export function allow(a:Actor,cap:string,city?:string){if(a.is_global)return;if(!a.capabilities?.[cap]||city&&!a.managementCities?.includes(city))throw new UserError('Operação fora das permissões do seu pelotão.',403);}
export function operate(a:Actor,city:string){if(!a.cities?.includes(city))throw new UserError('Município não autorizado para este acesso.',403);}
export async function generalOfficer(){return (await stmt("SELECT value FROM settings WHERE key='general_manager_officer_id'").first<{value:string}>())?.value||'';}
async function enrich(a:Actor,o:any):Promise<Actor>{const global=!!a.is_owner||!!o&&o.id===await generalOfficer();const memberships=o?await stmt('SELECT platoon_id FROM officer_platoons WHERE officer_id=? AND active=1',o.id).all<any>():{results:[]};const home=o?.home_platoon||'p4';const permissions=o?.permissions||{};const commander=['comando','comandante','administrador'].includes(a.role);const capabilities=Object.fromEntries(['materials','officers','movements','audit','global_status'].map(cap=>[cap,global||commander||a.role==='subcomandante'&&permissions[cap]===true]));capabilities.global_status=global||['comando','comandante','administrador'].includes(a.role)||permissions.global_status===true;return {...a,role:global?'gestor_geral':a.role,is_global:global,must_change_password:!a.is_owner&&!!o?.must_change_password,registration:o?.registration||'',home_platoon:home,permissions,capabilities,cities:global?[...CITIES]:PLATOONS.filter(p=>memberships.results.some(m=>m.platoon_id===p.id)).flatMap(p=>[...p.cities]),managementCities:global?[...CITIES]:a.role==='policial'?[]:[...(PLATOONS.find(p=>p.id===home)?.cities||[])]};}
export async function manageOfficer(a:Actor,o:any){if(a.is_global)return;if(!o||o.home_platoon!==a.home_platoon)throw new UserError('Este policial pertence a outro pelotão.',403);allow(a,'officers',o.city);}
export function readRecord(a:Actor,city:string,own:boolean){if(own)return;if(!a.is_global&&!a.managementCities?.includes(city))throw new UserError('Registro de outro pelotão não disponível para este acesso.',403);}
export async function ownerId(){return (await stmt("SELECT value FROM settings WHERE key='owner_user_id'").first<{value:string}>())?.value||'';}
export async function isProtectedOfficer(o:any){const root=await ownerId();if(!root||!o)return false;return o.id===await generalOfficer()||o.id===root||o.auth_user_id===root||!!await stmt('SELECT id FROM principals WHERE id=? AND officer_id=?',root,o.id).first();}
export async function mutableUser(id:string){if(id===await ownerId()||await isProtectedOfficer(await stmt('SELECT * FROM officers WHERE id=?',id).first()))throw new UserError('O perfil principal 4º Pelotão é protegido e não pode ser excluído ou ter seus privilégios alterados.',403);}
export function authAdmin(){const keys=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}');const key=keys.default||Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');const url=Deno.env.get('SUPABASE_URL');if(!key||!url)throw new UserError('O serviço de contas está indisponível.',503);return createClient(url,key,{auth:{persistSession:false,autoRefreshToken:false}});}
export function textValue(v:unknown,max=2000){return typeof v==='string'?v.trim().slice(0,max):'';}
export function integer(v:unknown,min=0,max=1000000){if(!Number.isInteger(v)||Number(v)<min||Number(v)>max)throw new UserError('Informe uma quantidade inteira válida.');return Number(v);}
export function auditStmt(a:Actor,action:string,entity:string,before:any,after:any,now=new Date().toISOString()){const city=after?.location||after?.city||after?.origin||before?.location||before?.city||null;return stmt('INSERT INTO audit(id,actor,actor_name,action,entity,before,after,created_at,actor_registration,city,platoon_id) VALUES(?,?,?,?,?,?,?,?,?,?,?)',crypto.randomUUID(),a.id,a.name,action,entity,before==null?null:JSON.stringify(before),after==null?null:JSON.stringify(after),now,a.registration||null,city,city?platoonOf(city):after?.home_platoon||before?.home_platoon||a.home_platoon||null);}
export function guard(id:string,query:string,...args:unknown[]){return stmt(`INSERT INTO operation_guards(id,ok) VALUES (?,CASE WHEN (${query}) THEN 1 ELSE 0 END)`,id,...args);}
export function clearGuard(id:string){return stmt('DELETE FROM operation_guards WHERE id=?',id);}
